apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: vod-ctrl-staging
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
