apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-demo
  namespace: vod-ctrl-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-demo
  template:
    metadata:
      labels:
        app: busybox-demo
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command: [ "sh", "-c", "while true; do sleep 3600; done" ]
          imagePullPolicy: IfNotPresent
